version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "4001:4001"
    env_file:
      - .env

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "4002:4002"
    env_file:
      - .env

  gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - order-service
    env_file:
      - .env

volumes:
  mongo_data:
